apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-7iwm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-7iwm@sha256:6fbf8d573d8d7ea788394261dfa78201ab2d56c06eb1a6bda3381252de0ddd4a
        name: my-python
        resources: {}
status: {}
